[tool.briefcase]
project_name = "ChatMe"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/chatme"
license = "BSD license"
author = 'Webster Avosa'
author_email = "websterb17@gmail.com"

[tool.briefcase.app.chatme]
formal_name = "ChatMe"
description = "My first application"
icon = "src/chatme/resources/chatme"
sources = ['src/chatme']
requires = []


[tool.briefcase.app.chatme.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.chatme.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.chatme.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.chatme.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.chatme.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
